
SELECT * 
FROM 
(SELECT EMP_NO,NULL AS EMP_PW,EMP_NM,EMP_ENGL_NM,BLT_DEPT_CD,JBLV_CD,PSTN_CD,'N' AS EXT_USER FROM TBL_CO_EMP_BS
UNION ALL
SELECT EMP_NO,EMP_PW,EMP_NM,EMP_ENGL_NM,BLT_DEPT_CD,JBLV_CD,PSTN_CD,'Y' AS EXT_USER FROM TBL_CO_EMP_BS_EXT) CO_EMP
LEFT JOIN TBL_CO_EMP_REG CO_REG
ON  CO_EMP.EMP_NO = CO_REG.EMP_NO;
